config/routes.rb
Rails.application.routes.draw do
  namespace :super_admin do
    resources :employees
  end
  namespace :admin do
    resources :employees
  end
  namespace :department_admin do
    resources :employees, only: [:index, :show]
  end

  devise_for :employees, controllers: {
  confirmations: 'employees/confirmations',
  passwords: 'employees/passwords',
  registrations: 'employees/registrations',
  sessions: 'employees/sessions',
  unlocks: 'employees/unlocks',
  # omniauth_callbacks: 'employees/omniauth_callbacks'
}
  devise_scope :employee do
    get '/employees/sign_out' => 'devise/sessions#destroy'
  end

  get 'pages/index'
  get 'help', to: 'pages#help'
  namespace :uploads do
    resources :driver_licenses, only: [:new, :create, :edit, :update]
    resources :vehicle_inspections, only: [:new, :create, :edit, :update]
    resources :compulsory_insurances, only: [:new, :create, :edit, :update]
    resources :optional_insurances, only: [:new, :create, :edit, :update]
    resources :documents, only: [:index]
  end
  # メインページ
  # root 'documents#index'

  root to: "pages#index"
  resources :employees, only: [:edit, :update, :show]
  resources :departments

  # get '*path', to: 'application#render404'
  # get '*path', to: 'application#render500'
  # 上のやつだと、アクティブストレージがパーになって動かないから下のに変更
  # https://qiita.com/xusaku_/items/8c8dc237dbbbcc116964
  get '*not_found' => 'application#render404', constraints: lambda { |request| !request.path.include?("active_storage") }
  post '*not_found' => 'application#render404', constraints: lambda { |request| !request.path.include?("active_storage") }

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/employee.rb
class Employee < ApplicationRecord
  has_one :driver_license, dependent: :destroy
  has_one :vehicle_inspection, dependent: :destroy
  has_one :compulsory_insurance, dependent: :destroy
  has_one :optional_insurance, dependent: :destroy

  belongs_to :department
  rolify
  after_create :assign_default_role
  before_destroy :dont_delete_last_super_admin, prepend: true
  # before_update :dont_edit_last_super_admin, prepend: true


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :name_kana, presence: true, format: { with: /\A[ぁ-んー－]+\z/, message: 'はひらがなのみ入力可能です。' }
  validates :employee_number, presence: true, uniqueness: true
  validates :department_id, presence: true


  # search
  scope :search, ->(search_params) {
    return if search_params.blank?

    search_name(search_params[:name])
      .search_number(search_params[:employee_number])
      .search_department(search_params[:department])
  }
# 名前と部署を同時にサーチする時、name LIKE?だとエラーが発生。
# 原因はnameというカラムがemployeeにもdepartmentにも存在し、どちらを検索すればいいのかわからなくなっちゃったらしい
# ここで解決：https://qiita.com/j-sunaga/items/99e576cca995b84a7839
  scope :search_name, ->(name) { where('employees.name LIKE ?', "%#{name}%") if name.present? }
  scope :search_number, ->(employee_number) { where('employee_number LIKE ?', "%#{employee_number}%") if employee_number.present? }
  scope :search_department, ->(department) { joins(:department).where(department: { id: department }) if department.present? }

  # メーラー
  def self.send_expiration_notifications
    Employee.includes(:driver_license, :vehicle_inspection, :compulsory_insurance, :optional_insurance).find_each do |employee|
      documents = []
      documents << employee.driver_license if employee.driver_license&.expiration_date == Date.today + 1.month
      documents << employee.vehicle_inspection if employee.vehicle_inspection&.expiration_date == Date.today + 1.month
      documents << employee.compulsory_insurance if employee.compulsory_insurance&.expiration_date == Date.today + 1.month
      documents << employee.optional_insurance if employee.optional_insurance&.expiration_date == Date.today + 1.month

      if documents.any?
        DocumentMailer.expiration_notification(employee, documents).deliver_now
      end
    end
  end

  # default role
  def assign_default_role
    self.add_role(:general) if self.roles.blank?
  end

  def update_role(role_id)
    # すでにrole持ってたら引数で受け取ったrole_nameにupdateする
    role = Role.find(role_id)
    role_name = role.name
    if self.roles.present?
      self.remove_role(self.roles.first.name)
    end
    self.add_role(role_name)
  end

  # アドミン消させないやつ

  def dont_delete_last_super_admin
    if has_role?(:super_admin) && Employee.with_role(:super_admin).count <= 1
      errors.add(:base, "スーパー管理者が一人になるため、ロールの削除ができませんでした。")
      throw(:abort)
    end
  end

  # 対象のroleがsuperadminじゃない時は無条件でupdateできる
  # superadmin数が2人以上だったらupdateできる
  def can_edit_last_super_admin(role_id)
    if roles.first.name != "super_admin" ||
      Employee.with_role(:super_admin).count > 1 ||
      (Employee.with_role(:super_admin).count <= 1 &&
      roles.first.id == role_id)
      return true
    end
    errors.add(:base, 'スーパー管理者が一人になるため、ロールの編集ができません。')
    return false
  end



  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    email = conditions.delete(:email)
    where(conditions.to_h).where(["lower(email) = :value", { value: email.downcase }]).first
  end
end

app/controllers/admin/employees_controller.rb
module Admin
  class EmployeesController < ApplicationController
    before_action :admin_required
    before_action :authenticate_employee!
    before_action :set_employee, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    def index
      @search_params = employee_search_params
      @employees = Employee.all.includes(:department, :driver_license, :vehicle_inspection, :compulsory_insurance, :optional_insurance).search(@search_params).page(params[:page])
    end

    def show
      @employee = Employee.find(params[:id])
    end

    def new
      @employee = Employee.new
    end

    def create
      @employee = Employee.new(employee_params)
      if @employee.save
        redirect_to admin_employees_path, notice: 'アカウントが作成されました'
      else
        render :new
      end
    end

    def edit
      if @employee.has_role?(:super_admin) && !current_employee.has_role?(:super_admin)
        redirect_to admin_employees_path, notice: '編集権限がありません'
      else
        render 'admin/employees/edit'
      end
    end

    def update
      if @employee.update(employee_params)
        redirect_to admin_employees_path, notice: 'アカウントが更新されました'
      else
        render :edit
      end
    end

    def destroy
      if @employee.has_role?(:super_admin) && !current_employee.has_role?(:super_admin)
        redirect_to admin_employees_path, notice: 'スーパー管理者の削除権限がありません'
      elsif @employee.destroy
        redirect_to admin_employees_path, notice: 'アカウントが削除されました'
      else
        redirect_to admin_employees_path, alert: @employee.errors.full_messages.to_sentence
      end
    end

    private

    def employee_search_params
      params.fetch(:search, {}).permit(:name, :employee_number, :department)
    end

    def admin_required
      unless current_employee&.has_role?(:admin)
        flash[:alert] = 'アクセス権限がありません'
        redirect_to pages_index_path
      end
    end

    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name,:name_kana,:employee_number, :department_id, :email, :password, :password_confirmation, :role_ids)
    end
  end
end

app/controllers/department_admin/employees_controller.rb
module DepartmentAdmin
  class EmployeesController < ApplicationController
    before_action :department_admin_required
    before_action :authenticate_employee!
    before_action :set_employee, only: [:show]
    load_and_authorize_resource

    def index
      @search_params = employee_search_params
      @employees = Employee.where(department: current_employee.department).includes(:department, :driver_license, :vehicle_inspection, :compulsory_insurance, :optional_insurance).search(@search_params).page(params[:page])
    end

    def show
      @employee = Employee.find(params[:id])
    end


    private

    def employee_search_params
      params.fetch(:search, {}).permit(:name, :employee_number)
    end

    def department_admin_required
      unless current_employee&.has_role?(:department_admin)
        flash[:alert] = 'アクセス権限がありません'
        redirect_to pages_index_path
      end
    end

    def set_employee
      @employee = Employee.find(params[:id])
    end

  end
end

app/controllers/employees/confirmations_controller.rb
# frozen_string_literal: true

class Employees::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/employees/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Employees::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employees/passwords_controller.rb
# frozen_string_literal: true

class Employees::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/employees/registrations_controller.rb
# frozen_string_literal: true

class Employees::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  protected

  def sign_up_params
    params.require(:employee).permit(:name, :employee_number, :department_id, :email, :password, :password_confirmation, :role)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :employee_number, :department_id])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :employee_number, :department_id])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employees/sessions_controller.rb
# frozen_string_literal: true

class Employees::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/employees/unlocks_controller.rb
# frozen_string_literal: true

class Employees::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_employee!
  before_action :set_employee, only: [:show, :edit, :update]

  def edit

  end

  def update

    if @employee.update(employee_params)
      sign_in :employee, @employee, bypass: true
      redirect_to employee_path(@employee), notice: 'Employee was successfully updated.'
    else
      render :edit
    end
  end



  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    if current_employee.has_role?(:super_admin) || current_employee.has_role?(:admin) || current_employee.has_role?(:department_admin)
      params.require(:employee).permit(:name,:name_kana,:employee_number, :department_id, :email, :password, :password_confirmation, :role_ids)
    else
      params.require(:employee).permit(:email, :password, :password_confirmation)
    end
  end
end

app/controllers/super_admin/employees_controller.rb
module SuperAdmin
  class EmployeesController < ApplicationController
    before_action :super_admin_required
    before_action :authenticate_employee!
    before_action :set_employee, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    def index
      @search_params = employee_search_params
      @employees = Employee.all
      .includes(:department, :driver_license, :vehicle_inspection, :compulsory_insurance, :optional_insurance)
      .search(@search_params).page(params[:page])
    end

    def show
      @employee = Employee.find(params[:id])
    end

    def new
      @employee = Employee.new
    end

    def create
      @employee = Employee.new(employee_params)
      if @employee.save
        redirect_to super_admin_employees_path, notice: 'アカウントが作成されました'
      else
        render :new
      end
    end

    def edit
      render 'super_admin/employees/edit'
    end

    def update

      if @employee.can_edit_last_super_admin(employee_params[:role_ids].to_i)
        @employee.update(employee_params)
        @employee.update_role(employee_params[:role_ids])
        #binding.irb
        redirect_to super_admin_employees_path, notice: 'アカウントが更新されました'
      else
        #@employee.errors.add(:base, 'スーパー管理者が一人になるため、ロールの編集ができません。')
        render :edit
      end
    end

    def destroy
      if @employee.has_role?(:super_admin) && !current_employee.has_role?(:super_admin)
        redirect_to super_admin_employees_url, alert: '管理者はスーパー管理者を削除できません'
      elsif @employee.destroy
        redirect_to super_admin_employees_path, notice: 'アカウントが削除されました'
      else
        redirect_to super_admin_employees_url, alert: @employee.errors.full_messages.to_sentence
    end
    end

    private

    # sort_order = params[:sort] == 'desc' ? :desc : :asc

    def employee_search_params
      params.fetch(:search, {}).permit(:name, :employee_number, :department)
    end

    def super_admin_required
      unless current_employee&.has_role?(:super_admin)
        flash[:alert] = 'アクセス権限がありません'
        redirect_to pages_index_path
      end
    end

    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name,:name_kana,:employee_number, :department_id, :email, :password, :password_confirmation, :role_ids)
    end
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/admin/employees/edit.html.erb
<h2><%= t('employees.edit.title') %></h2>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-7">
      <%= form_for([:admin, @employee], html: { class: 'form-horizontal' }) do |f| %>
        <% if @employee.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <div id="error_explanation">
              <h4><%= pluralize(@employee.errors.count, "つ") %> のエラーが発生しました:</h4>
              <ul>
                <% @employee.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :name, Employee.human_attribute_name(:name), class: 'col-form-label' %><br />
          <%= f.text_field :name, autofocus: true, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :name_kana, Employee.human_attribute_name(:name_kana), class: 'col-form-label' %><br />
          <%= f.text_field :name_kana, autofocus: true, class: 'form-control' %>
        </div>
        <div class="form-row">
          <div class="form-group col-md-3">
            <%= f.label :department, Employee.human_attribute_name(:department), class: 'col-form-label' %><br />
            <%= f.collection_select :department_id, Department.all, :id, :name, { prompt: "選択" }, { class: 'form-control' } %>
          </div>
          <div class="form-group col-md-9">
            <%= f.label :employee_number, Employee.human_attribute_name(:employee_number), class: 'col-form-label' %><br />
            <%= f.text_field :employee_number, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :email, Employee.human_attribute_name(:email), class: 'col-form-label' %><br />
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password, Employee.human_attribute_name(:password), class: 'col-form-label' %>
          <% if @minimum_password_length %>
            <small class="form-text text-muted">(<%= @minimum_password_length %>文字以上)</small>
          <% end %><br />
          <%= f.password_field :password, autocomplete: "new-password", class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, Employee.human_attribute_name(:password_confirmation), class: 'col-form-label' %><br />
          <%= f.password_field :password_confirmation, autocomplete: "new-password", class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "作成", class: 'btn btn-primary btn-block btn-custom mt-5' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/employees/index.html.erb
<% content_for :title, t('employees.index.title') %>
<h1 class="my-4"><%= t('employees.index.title') %></h1>
<%= link_to t('employees.index.new'), new_admin_employee_path, class: "btn btn-primary mb-3" %>
<div class="search_field mb-4">
  <%= form_with url: admin_employees_path, method: :get, scope: :search, local: true do |form| %>
    <div class="form-row">
      <div class="form-group col-md-4">
        <%= form.label :name, Employee.human_attribute_name(:name) %>
        <%= form.text_field :name, value: @search_params[:name], class: "form-control" %>
      </div>
      <div class="form-group col-md-4">
        <%= form.label :employee_number, Employee.human_attribute_name(:employee_number) %>
        <%= form.text_field :employee_number, value: @search_params[:employee_number], class: "form-control" %>
      </div>
      <div class="form-group col-md-4">
        <%= form.label :department, Employee.human_attribute_name(:department) %>
        <%= form.select :department, options_for_select(Department.all.map { |department| [department.name, department.id] }, selected: @search_params[:department]), { include_blank: true }, class: "form-control" %>
      </div>
    </div>
    <div class="form-row justify-content-end">
      <div class="form-group">
        <%= form.submit t('employees.index.search'), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>
<div class= 'text-right'>
  <button class="btn btn-secondary mb-3" type="button" data-toggle="collapse" data-target=".extra-columns" aria-expanded="false" aria-controls="extra-columns">
    列を表示/非表示
  </button>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Employee.human_attribute_name(:name) %></th>
      <th class="collapse extra-columns"><%= Employee.human_attribute_name(:employee_number) %></th>
      <th class="collapse extra-columns"><%= Employee.human_attribute_name(:department) %></th>
      <th><%= t('employees.index.driver_license_expiration') %></th>
      <th><%= t('employees.index.vehicle_inspection_expiration') %></th>
      <th><%= t('employees.index.compulsory_insurance_expiration') %></th>
      <th><%= t('employees.index.optional_insurance_expiration') %></th>
      <th class="collapse extra-columns"><%= t('employees.index.role') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td class="collapse extra-columns"><%= employee.employee_number %></td>
        <td class="collapse extra-columns"><%= employee.department.name %></td>
        <td><%= employee.driver_license&.expiration_date %></td>
        <td><%= employee.vehicle_inspection&.expiration_date %></td>
        <td><%= employee.compulsory_insurance&.expiration_date %></td>
        <td><%= employee.optional_insurance&.expiration_date %></td>
        <td class="collapse extra-columns"><%= employee.roles.map { |role| I18n.t("roles.#{role.name}") }.join(', ') %></td>
        <td><%= link_to t('employees.index.show'), admin_employee_path(employee), class: "btn btn-info btn-sm" %></td>
        <td><%= link_to t('employees.index.edit'), edit_admin_employee_path(employee), class: "btn btn-warning btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="d-flex justify-content-center">
  <%= paginate @employees %>
</div>

app/views/admin/employees/new.html.erb
<h2><%= t('employees.new.title') %></h2>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-7">
      <%= form_for([:admin, @employee], html: { class: 'form-horizontal' }) do |f| %>
        <% if @employee.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <div id="error_explanation">
              <h4><%= pluralize(@employee.errors.count, "つ") %> のエラーが発生しました:</h4>
              <ul>
                <% @employee.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :name, Employee.human_attribute_name(:name), class: 'col-form-label' %><br />
          <%= f.text_field :name, autofocus: true, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :name_kana, Employee.human_attribute_name(:name_kana), class: 'col-form-label' %><br />
          <%= f.text_field :name_kana, autofocus: true, class: 'form-control' %>
        </div>
        <div class="form-row">
          <div class="form-group col-md-3">
            <%= f.label :department, Employee.human_attribute_name(:department), class: 'col-form-label' %><br />
            <%= f.collection_select :department_id, Department.all, :id, :name, { prompt: "選択" }, { class: 'form-control' } %>
          </div>
          <div class="form-group col-md-9">
            <%= f.label :employee_number, Employee.human_attribute_name(:employee_number), class: 'col-form-label' %><br />
            <%= f.text_field :employee_number, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :email, Employee.human_attribute_name(:email), class: 'col-form-label' %><br />
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password, Employee.human_attribute_name(:password), class: 'col-form-label' %>
          <% if @minimum_password_length %>
            <small class="form-text text-muted">(<%= @minimum_password_length %>文字以上)</small>
          <% end %><br />
          <%= f.password_field :password, autocomplete: "new-password", class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, Employee.human_attribute_name(:password_confirmation), class: 'col-form-label' %><br />
          <%= f.password_field :password_confirmation, autocomplete: "new-password", class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "作成", class: 'btn btn-primary btn-block btn-custom mt-5' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/employees/show.html.erb
<h2><%= t('employees.show.title') %></h2>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-9">
      <p>名前： <%= @employee.name %></p>
      <p>かな： <%= @employee.name_kana %></p>
      <p>社員番号： <%= @employee.employee_number %></p>
      <p>所属部署：<%= @employee.department.name %></p>
      <p>メールアドレス: <%= @employee.email %></p>
      <p>ロール： <%= @employee.roles.map { |role| I18n.t("roles.#{role.name}") }.join(', ') %></p>
      <div class="text-right">
        <% if @employee.has_role?(:super_admin) %>
          <p>編集/削除権限はありません</p>
        <% else %>
          <%= link_to '編集', edit_admin_employee_path(@employee), class: "btn btn-warning mr-2" %>
          <%= link_to '削除', admin_employee_path(@employee), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger' %>
        <% end %>
      </div>
      <table class="table table-striped mt-4">
        <thead>
          <tr>
            <th><%= t('employees.index.driver_license_expiration') %></th>
            <th><%= t('employees.index.vehicle_inspection_expiration') %></th>
            <th><%= t('employees.index.compulsory_insurance_expiration') %></th>
            <th><%= t('employees.index.optional_insurance_expiration') %></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @employee.driver_license&.expiration_date %></td>
            <td><%= @employee.vehicle_inspection&.expiration_date %></td>
            <td><%= @employee.compulsory_insurance&.expiration_date %></td>
            <td><%= @employee.optional_insurance&.expiration_date %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>