config/routes.rb
Rails.application.routes.draw do
  namespace :super_admin do
    resources :employees
  end
  namespace :admin do
    resources :employees
  end
  namespace :department_admin do
    resources :employees, only: [:index, :show]
  end

  devise_for :employees, controllers: {
  confirmations: 'employees/confirmations',
  passwords: 'employees/passwords',
  registrations: 'employees/registrations',
  sessions: 'employees/sessions',
  unlocks: 'employees/unlocks',
  # omniauth_callbacks: 'employees/omniauth_callbacks'
}
  devise_scope :employee do
    get '/employees/sign_out' => 'devise/sessions#destroy'
  end

  get 'pages/index'
  get 'help', to: 'pages#help'
  namespace :uploads do
    resources :driver_licenses, only: [:new, :create, :edit, :update]
    resources :vehicle_inspections, only: [:new, :create, :edit, :update]
    resources :compulsory_insurances, only: [:new, :create, :edit, :update]
    resources :optional_insurances, only: [:new, :create, :edit, :update]
    resources :documents, only: [:index]
  end
  # メインページ
  # root 'documents#index'

  root to: "pages#index"
  resources :employees, only: [:edit, :update, :show]
  resources :departments

  # get '*path', to: 'application#render404'
  # get '*path', to: 'application#render500'
  # 上のやつだと、アクティブストレージがパーになって動かないから下のに変更
  # https://qiita.com/xusaku_/items/8c8dc237dbbbcc116964
  get '*not_found' => 'application#render404', constraints: lambda { |request| !request.path.include?("active_storage") }
  post '*not_found' => 'application#render404', constraints: lambda { |request| !request.path.include?("active_storage") }

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employees

  validates :name, presence: true, uniqueness: true
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :authenticate_employee!
  before_action :authorize_admins!
  before_action :set_department, only: %i[edit update destroy]


  def index
    @departments = Department.all
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path, notice: '部署が作成されました'
    else
      render :new
    end
  end

  def edit
    @department = Department.find(params[:id])
  end

  def update
    if @department.update(department_params)
      redirect_to departments_path, notice: '部署が編集されました'
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path, notice: '部署が削除されました'
  end

  private

  def authorize_admins!
    unless  current_employee.has_role?(:admin) || current_employee.has_role?(:super_admin)
      redirect_to root_path, alert: 'アクセス権限がありません。'
    end
  end

  def set_department
    @department = Department.find(params[:id])
  end

  def department_params
    params.require(:department).permit(:name)
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-7">
      <h1>編集</h1>
      <%= form_for(@department, html: { class: 'form-horizontal' }) do |f| %>
        <% if @department.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <div id="error_explanation">
              <h4><%= pluralize(@department.errors.count, "つ") %> のエラーが発生しました:</h4>
              <ul>
                <% @department.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :name, Department.human_attribute_name(:name), class: 'col-form-label' %><br />
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <div class="text-right">
            <%= f.submit '部署を編集', class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
      <%= link_to '戻る', departments_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/departments/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1>部署リスト</h1>
      <div class="text-right">
        <%= link_to '新しい部署を作る', new_department_path, class: 'btn btn-primary mb-3' %>
      </div>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>部署名</th>
          </tr>
        </thead>
        <tbody>
          <% @departments.each do |department| %>
            <tr>
              <td><%= department.name %></td>
              <td>
                <div class="text-right">
                  <%= link_to '編集', edit_department_path(department), class: 'btn btn-warning btn-sm' %>
                  <%= link_to '削除', department, method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger btn-sm' %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/departments/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1>新規作成</h1>
      <%= form_for(@department, html: { class: 'form-horizontal' }) do |f| %>
        <% if @department.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <div id="error_explanation">
              <h4><%= pluralize(@department.errors.count, "つ") %> のエラーが発生しました:</h4>
              <ul>
                <% @department.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :name, Department.human_attribute_name(:name), class: 'col-form-label' %><br />
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <div class="text-right">
            <%= f.submit '部署を作成', class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
      <%= link_to '戻る', departments_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>