config/routes.rb
Rails.application.routes.draw do
  namespace :super_admin do
    resources :employees
  end
  namespace :admin do
    resources :employees
  end
  namespace :department_admin do
    resources :employees, only: [:index, :show]
  end

  devise_for :employees, controllers: {
  confirmations: 'employees/confirmations',
  passwords: 'employees/passwords',
  registrations: 'employees/registrations',
  sessions: 'employees/sessions',
  unlocks: 'employees/unlocks',
  # omniauth_callbacks: 'employees/omniauth_callbacks'
}
  devise_scope :employee do
    get '/employees/sign_out' => 'devise/sessions#destroy'
  end

  get 'pages/index'
  get 'help', to: 'pages#help'
  namespace :uploads do
    resources :driver_licenses, only: [:new, :create, :edit, :update]
    resources :vehicle_inspections, only: [:new, :create, :edit, :update]
    resources :compulsory_insurances, only: [:new, :create, :edit, :update]
    resources :optional_insurances, only: [:new, :create, :edit, :update]
    resources :documents, only: [:index]
  end
  # メインページ
  # root 'documents#index'

  root to: "pages#index"
  resources :employees, only: [:edit, :update, :show]
  resources :departments

  # get '*path', to: 'application#render404'
  # get '*path', to: 'application#render500'
  # 上のやつだと、アクティブストレージがパーになって動かないから下のに変更
  # https://qiita.com/xusaku_/items/8c8dc237dbbbcc116964
  get '*not_found' => 'application#render404', constraints: lambda { |request| !request.path.include?("active_storage") }
  post '*not_found' => 'application#render404', constraints: lambda { |request| !request.path.include?("active_storage") }

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>MyCarDocumentApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-custom-blue">
        <% if employee_signed_in? %>
          <% if current_employee.has_role?(:super_admin)  %>
            <%= link_to 'MyCarDocumentApp!!', root_path, class: 'navbar-brand' %>
          <% elsif current_employee.has_role?(:admin) %>
            <%= link_to 'MyCarDocumentApp!', root_path, class: 'navbar-brand' %>
          <% else %>
            <%= link_to 'MyCarDocumentApp', root_path, class: 'navbar-brand' %>
          <% end %>
        <% else %>
          <%= link_to 'MyCarDocumentApp', new_employee_session_path, class: 'navbar-brand' %>
        <% end %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to help_path, class: 'nav-link help-icon' do %>
              <span>
                ?
              </span>
            <% end %>
          </li>
        </ul>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
            <% if employee_signed_in? %>
              <% if current_employee.has_role?(:super_admin) %>
                <li class="nav-item"><%= link_to '社員一覧', super_admin_employees_path, class: "nav-link btn btn-primary", id: 'SAdmin-EmpList'  %></li>
                <li class="nav-item"><%= link_to '部署一覧', departments_path, class: "nav-link btn btn btn-primary", id: 'SAdmin-DeptList'  %></li>
                <li class="nav-item"><%= link_to '新しい社員', new_super_admin_employee_path, class: "nav-link btn  btn-primary", id: 'SAdmin-NewEmp'  %></li>
              <% elsif current_employee.has_role?(:admin) %>
                <li class="nav-item"><%= link_to '社員一覧', admin_employees_path, class: "nav-link btn btn btn-primary", id: 'Admin-EmpList' %></li>
                <li class="nav-item"><%= link_to '部署一覧', departments_path, class: "nav-link btn btn-primary", id: 'Admin-DeptList' %></li>
                <li class="nav-item"><%= link_to '新しい社員', new_admin_employee_path, class: "nav-link btn btn-primary", id: 'Admin-NewEmp' %></li>
              <% elsif current_employee.has_role?(:department_admin) %>
                <li class="nav-item"><%= link_to '社員一覧', department_admin_employees_path, class: "nav-link btn btn-primary", id: 'DeptAdmin-EmpList' %></li>
              <% else %>
                <li class="nav-item"><%= link_to '書類', uploads_documents_path, class: "nav-link btn btn-primary", id: 'my-document' %></li>
                <li class="nav-item"><%= link_to 'マイアカウント', employee_path(current_employee), class: "nav-link btn btn-primary" ,id: 'my-account'%></li>
              <% end %>
              <li class="nav-item"><%= link_to 'ログアウト', destroy_employee_session_path, method: :delete, class: "nav-link btn btn-primary" ,id: 'sign-out'%></li>
            <% else %>
              <li class="nav-item"><%= link_to 'ログイン', new_employee_session_path, class: "nav-link btn btn-primary", id: 'sign-in' %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <div class="container mt-4">
      <p class="notice alert alert-info <%= notice.blank? ? 'd-none' : '' %>"><%= notice %></p>
      <p class="alert alert-danger <%= alert.blank? ? 'd-none' : '' %>"><%= alert %></p>
      <%= yield %>
    </div>
    <footer class="footer bg-light py-3 mt-5 mb-auto">
      <div class="container">
        <div class="text-right">
          <p class="text-muted">MyCarDocumentApp</p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Error</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>